### ISSUE TITLE
Tests are not idempotent

### ISSUE THREAD

**Issue by irl** [mikeperry-tor/vanguards#14]
`tests/test_main.py` leaves behind a `valid` and `vanguards.state` file after running. Can these be temporary files instead?

**Comment by mikeperry-tor** [comment]
Is removing these files at the end of the test sufficient? Or do you want them to be actual mktemp() files in /tmp?

There is also I think a related issue where tests/state.mock gets modified by the tests.. Fixing that will involve quite a bit of juggling.

How much of a blocker is this to packaging? Is this just an annoyance, a debian policy violation, or a full technical blocker?

**Comment by mikeperry-tor** [comment]
Ok I think that commit should take care of the stray and modified files. Let me know if there are any more instances. Also let me know if you want a new release tag for this.

**Comment by irl** [comment]
This seems to have fixed the issue. The initial Debian packaging is just coming off a git snapshot, so a new release tag is not required.
