### ISSUE TITLE
Reconnect if control port closes/fails

### ISSUE THREAD

**Issue by mikeperry-tor** [mikeperry-tor/vanguards#19]
If Tor is restarted due to an update, vanguards will just exit because the control port closes.

Should we keep reconnecting in that case (and for how long), or should this be systemd's (or init's) job to restart us if Tor is restarted?

**Comment by irl** [comment]
It is possible to restart the service if it exits with systemd, but this will only happen so many times before systemd decides it's not going to start again. If tor takes a while to start up, that limit may be reached before it connects. Ideally vanguards should keep attempting to connect indefinitely, with some sleep in between attempts.

**Comment by mikeperry-tor** [comment]
Ok this should be fixed in master now. We keep on trying to reconnect every second forever, unless --retry-limit N is passed as a command line argument.
