### ISSUE TITLE
[warn] Requested exit point '$01D3B71F140FFEC3A0C1FE84A656AE7697971EA4' is not known. Closing.

### ISSUE THREAD

**Issue by asn-d6** [mikeperry-tor/vanguards#28]
Got this on my HSv3 logs today:
```
[warn] Requested exit point '$01D3B71F140FFEC3A0C1FE84A656AE7697971EA4' is not known. Closing.
```

I'm running f3c27c7fd84f51ae14625df0df5bb7b567a6fcd1 so perhaps the bug has been fixed?

**Comment by mikeperry-tor** [comment]
This line looks like it is coming from circuit_get_open_circ_or_launch() for purpose HSDIR_GET or HSDIR_POST.

The vanguards addon should not be picking exit points for these two. I am not sure why this would fail.

**Comment by asn-d6** [comment]
Hmm, I scanned the vanguards logs and it doesn't seem related given the relay fingerprint.

I'm gonna close this ticket and if it reappears, I will investigate further.
