### ISSUE TITLE
Repo is using different guard topology than prop292

### ISSUE THREAD

**Issue by asn-d6** [mikeperry-tor/vanguards#4]
Prop292 says we are using 2-4-6, whereas this repo seems to be using 2-3-8.

**Comment by asn-d6** [comment]
I made a PR doing the change. Feel free to merge it or ignore it for now.

**Comment by mikeperry-tor** [comment]
I thought that https://trac.torproject.org/projects/tor/ticket/25545 meant that we wanted to do either 2-3-8 or 2-4-8, depending on performance results?

**Comment by asn-d6** [comment]
Ha! That's true. In that case I guess that we need to change prop292 :)

I guess we are waiting for performance benchmarks before doing so.

Closing this issue.
