### ISSUE TITLE
SIGHUP signal will clear vanguards

### ISSUE THREAD

**Issue by mikeperry-tor** [mikeperry-tor/vanguards#40]
We need to watch the SIGNAL event for the RELOAD signal, and reapply vanguards on the event of it. Otherwise, when Tor gets HUP signals, we'll lose vanguards.

**Comment by exploreexplo** [comment]
Does vanguards continue to work in the background when we close terminal?

**Comment by mikeperry-tor** [comment]
> Does vanguards continue to work in the background when we close terminal?

No. Your two options are to use a systemd service, like the debian/testing package does: https://salsa.debian.org/pkg-privacy-team/vanguards/blob/master/debian/vanguards.service

or use --oneshot_vanguards from an hourly cron script (which only provides you with the path selection defenses, not the dropped cell ones).

**Comment by exploreexplo** [comment]
> No. Your two options are to use a systemd service, like the debian/testing package does: https://salsa.debian.org/pkg-privacy-team/vanguards/blob/master/debian/vanguards.service

Thanks for this.  How can I use this with vanguards?

**Comment by mikeperry-tor** [comment]
> > No. Your two options are to use a systemd service, like the debian/testing package does: https://salsa.debian.org/pkg-privacy-team/vanguards/blob/master/debian/vanguards.service
> 
> Thanks for this. How can I use this with vanguards?

There are vanguards packages in debian/testing which should become the new debian/stable very soon. They should also be available in debian/backports very shortly (for debian 9.0 users). 

This issue is fixed in vanguards 0.3.1. If you have packaging issues, file another ticket.
