### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by Obire** [mikeperry-tor/vanguards#41]
Hi, do you have contact details you can provide such as an email address? Vanguards has helped me extremely with a variety of attacks, I need to make a commissioned request if possible please, would be really appreciated and is related to an unknown attack vector.

**Comment by Obire** [comment]
It might be worth me adding that the idea for it I have already theorized/planned, it would just need building and I do not have the means to develop it.

**Comment by mikeperry-tor** [comment]
This strikes me as odd. This is not usually how we do work. Also, if you have the git repo, my email address is in the commit messages. Remove the -git.

However, I don't do commissioned work just for the sake of payment. The decision to implement your idea will depend on what your attack/issue is, and how important it seems to implement that particular defense idea in vanguards. Also: if your defense depends on it remaining a secret, then that's definitely not the type of work that I do (https://en.wikipedia.org/wiki/Kerckhoffs%27s_principle).

**Comment by Obire** [comment]
I did try to email you at the listed email and it failed, is that email address definitely still active?

**Comment by mikeperry-tor** [comment]
Yes, it works. You got a bounce from email?

**Comment by mikeperry-tor** [comment]
I'm closing this. If you have a specific feature request or attack vector, you can file a ticket or email tor-security@lists.torproject.org either encrypted or unencrypted.


If you want to PGP encrypt your mail, use this key:
pub   4096R/E135A8B41A7BF184 2017-03-13
      Key fingerprint = 8B90 4624 C5A2 8654 E453  9BC2 E135 A8B4 1A7B F184
uid                          tor-security@lists.torproject.org <tor-security@lists.torproject.org>

**Comment by mikeperry-tor** [comment]
Oh, also **YOU** can get paid if what you have is a security vulnerability on Tor that we don't know about: https://hackerone.com/torproject

If for some reason your issue excluded by that bug bounty program, please let me know what category it is excluded for.
