### ISSUE TITLE
use Tor ControlSocket unix domain socket file by default

### ISSUE THREAD

**Issue by adrelanos** [mikeperry-tor/vanguards#47]
Making use of vanguards is unfortunately not a `sudo apt install vanguards` experience. There is one small detail preventing that.

Debian `/usr/share/tor/tor-service-defaults-torrc` uses by default:

```
DataDirectory /var/lib/tor
PidFile /run/tor/tor.pid
RunAsDaemon 1
User debian-tor

ControlSocket /run/tor/control GroupWritable RelaxDirModeCheck
ControlSocketsGroupWritable 1
SocksPort unix:/run/tor/socks WorldWritable
SocksPort 9050

CookieAuthentication 1
CookieAuthFileGroupReadable 1
CookieAuthFile /run/tor/control.authcookie

Log notice syslog
```

By making the [confg](https://github.com/mikeperry-tor/vanguards/blob/master/vanguards-example.conf) use `control_socket` by default it could be come a `sudo apt install vanguards` experience.

I guess most distributions have moved on to `ControlSocket` rather than `ControlPort` by now?

**Comment by mikeperry-tor** [comment]
Hrmm.. the thing that makes me wary of this is the path to the control socket.. Even if most distros have a default socket, I bet the paths differ?

If they don't, then I can merge this. But I bet they do.

**Comment by mikeperry-tor** [comment]
After letting this sit for a while, and checking my linux distro, I don't think we can easily pick a standard default path here. We could do a list of common paths, perhaps, and test those. But that may be unsafe...
