### ISSUE TITLE
[notice] No circuits are opened. Relaxed timeout for circuit 48 (a Measuring circuit timeout 4-hop circuit in state doing handshakes with channel state open) to 60000ms. However, it appears the circuit has timed out anyway.

### ISSUE THREAD

**Issue by asn-d6** [mikeperry-tor/vanguards#8]
In my HS that uses vanguards, I get a few of those per-day:
```
[notice] No circuits are opened. Relaxed timeout for circuit 48 (a Measuring circuit timeout 4-hop circuit in state doing handshakes with channel state open) to 60000ms. However, it appears the circuit has timed out anyway.
```

I don't think I was getting those with vanguards disabled. I guess this is a tor issue, right? Any idea what's going on?

**Comment by mikeperry-tor** [comment]
Hrmm., the any_opened_circuits flag that triggers this is set based on DEFAULT_ROUTE_LEN.. So Tor will think you don't have any circuits opened if all you have are vanguard circuits. Are you only using hidden service circuits on this tor client?

That doesn't explain the reason that so many of these are timing out. Maybe set the vanguard loglevel to DEBUG and grep for those circ ids in the logs to see what they are doing? It is possible that one of your vanguards is down/really slow..

**Comment by asn-d6** [comment]
Yes, it's a hidden service so there are only HS circuits. Perhaps we should do something about `circuit_any_opened_circuits()`.

It wouldn't surprise me if some of those vanguards are down. I stopped using the script some time ago and just pinned a few vanguards with `HSLayer2Nodes`. I don't even remember why  I did that, but I don't think we should have warns if one node is down, should we?

**Comment by mikeperry-tor** [comment]
I am going to close this. If anything, since you weren't using this script, it is a tor-side bug. However, I do think Tor should complain a lot if you choose HSLayerNodes and other things that prevent it from building any paths, so maybe not even a tor bug. OTOH, if this does happen while the script is connected and rotating nodes, we should look deepr into any_opened_circuits() and file a Tor bug.
